# Generated by Django 5.0.6 on 2026-08-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bkash_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_trx_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
